#!/usr/bin/env bash
# Generates docker-compose.yml and caddy/Caddyfile from tenants.conf and state/.
#
#   tenants.conf   one line per tenant: <name> <public port> <uploads dir>
#   state/<name>   blue | green: the slot the proxy sends traffic to. Tenants
#                  without a state file get no proxy site yet (migration).
#
# Each tenant has two backend services, <name>-blue (port + 10000) and
# <name>-green (port + 20000), in the "backends" profile so a bare
# `docker compose up -d` only starts the proxy. Caddy listens on every public
# port (127.0.0.1) and forwards to the live slot.
set -euo pipefail
cd "$(dirname "$(readlink -f "$0")")"
[ -f tenants.conf ] || { echo "No tenants.conf"; exit 1; }
mkdir -p state caddy

TENANTS=()
while read -r name port uploads; do
  [[ -z "$name" || "$name" == \#* ]] && continue
  [[ "$name" =~ ^[a-z0-9_]+$ && "$port" =~ ^[0-9]+$ && "$uploads" == /* ]] || { echo "Bad tenants.conf line: $name $port $uploads"; exit 1; }
  TENANTS+=("$name $port $uploads")
done < tenants.conf

{
  cat <<'YAML'
# GENERATED by render.sh from tenants.conf: edit that file and rerun render.sh.
x-backend: &backend
  image: webcoop/esstrapis-back:${BACK_TAG:-v5}
  profiles: ["backends"]
  restart: unless-stopped
  network_mode: host
  stop_grace_period: 30s
  mem_limit: 1536m
  logging:
    driver: json-file
    options: { max-size: 10m, max-file: "3" }

services:
  proxy:
    image: caddy:2.11.4-alpine
    container_name: esstrapis-back-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./caddy:/etc/caddy:ro
      - caddy-data:/data
      - caddy-config:/config
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://127.0.0.1:2019/config/"]
      interval: 30s
      timeout: 5s
YAML
  for line in "${TENANTS[@]}"; do
    read -r name port uploads <<<"$line"
    for color in blue green; do
      p=$([ $color = blue ] && echo $((port + 10000)) || echo $((port + 20000)))
      cat <<YAML

  $name-$color:
    <<: *backend
    container_name: esstrapis-back-$name-$color
    env_file: envs/$name.env
    environment:
      PORT: "$p"
    volumes:
      - $uploads:/opt/app/public/uploads
YAML
    done
  done
  printf '\nvolumes:\n  caddy-data:\n  caddy-config:\n'
} > docker-compose.yml.new && mv docker-compose.yml.new docker-compose.yml

{
  cat <<'CADDY'
# GENERATED by render.sh from tenants.conf and state/: do not edit.
{
	admin 127.0.0.1:2019
	auto_https off
	default_bind 127.0.0.1
	servers {
		# nginx in front: keep its X-Forwarded-For/Proto (Strapi needs https for secure cookies).
		trusted_proxies static 127.0.0.1/32 ::1/128
	}
}
CADDY
  for line in "${TENANTS[@]}"; do
    read -r name port uploads <<<"$line"
    [ -f "state/$name" ] || continue
    color=$(cat "state/$name")
    p=$([ "$color" = green ] && echo $((port + 20000)) || echo $((port + 10000)))
    cat <<CADDY

# $name ($color)
:$port {
	reverse_proxy 127.0.0.1:$p {
		lb_try_duration 30s
		lb_try_interval 250ms
	}
}
CADDY
  done
} > caddy/Caddyfile.new && mv caddy/Caddyfile.new caddy/Caddyfile
