#!/usr/bin/env bash
#
# Adds IS_PROXIED=true to tenants that were prepared before config/server.js
# gained server.proxy.koa, and restarts them.
#
# Without it, Koa does not trust nginx's X-Forwarded-Proto, so the secure
# refresh-token cookie users-permissions sets on a successful login throws and
# POST /api/auth/local returns 500. Tenants prepared after that commit already
# get IS_PROXIED from vps-migrate-tenant.sh; this is only for the ones already
# cut over.
#
# Usage:
#   ./vps-set-proxied.sh ~/pm2-apps/strapi-projectes-{buida,demo,webcoop}-v5.config.js
#
# Idempotent: re-running on an already-patched tenant changes nothing and still
# reports what it found.
set -euo pipefail

[ "$#" -gt 0 ] || { echo "usage: vps-set-proxied.sh <v5-pm2-config.js>..." >&2; exit 1; }

RESTART="${RESTART:-1}"

for CONFIG_FILE in "$@"; do
  if [ ! -f "$CONFIG_FILE" ]; then
    echo "!! $CONFIG_FILE: no such file" >&2
    exit 1
  fi

  echo "== $CONFIG_FILE"

  # The pm2 config is the source of truth for both the app name and the cwd
  # that holds .env, so read them from it rather than reconstructing paths.
  read -r APP_NAME APP_CWD CHANGED < <(node -e '
    const fs = require("fs");
    // require() treats a bare relative path as a module name, so resolve first.
    const p = require("path").resolve(process.argv[1]);
    const cfg = require(p);
    const app = (cfg.apps || [])[0];
    if (!app) { console.error("no apps[] entry in " + p); process.exit(1); }
    app.env = app.env || {};
    const changed = app.env.IS_PROXIED === "true" ? "already-set" : "set";
    if (changed === "set") {
      app.env.IS_PROXIED = "true";
      fs.writeFileSync(p,
        "// generated by vps-migrate-tenant.sh — v3 config left untouched\n" +
        "module.exports = " + JSON.stringify(cfg, null, 2) + ";\n");
    }
    console.log([app.name, app.cwd, changed].join(" "));
  ' "$CONFIG_FILE")

  chmod 600 "$CONFIG_FILE"
  echo "   pm2 env: $CHANGED ($APP_NAME)"

  ENV_FILE="$APP_CWD/.env"
  if [ -f "$ENV_FILE" ]; then
    if grep -q '^IS_PROXIED=' "$ENV_FILE"; then
      sed -i 's|^IS_PROXIED=.*|IS_PROXIED=true|' "$ENV_FILE"
      echo "   .env:    updated"
    else
      printf 'IS_PROXIED=true\n' >> "$ENV_FILE"
      echo "   .env:    appended"
    fi
    chmod 600 "$ENV_FILE"
  else
    echo "   .env:    !! not found at $ENV_FILE" >&2
  fi

  if [ "$RESTART" = "1" ]; then
    # --update-env is what actually re-reads app.env; a plain restart reuses
    # the environment pm2 captured at start.
    pm2 restart "$APP_NAME" --update-env
    echo "   restarted $APP_NAME"
  else
    echo "   restart skipped (RESTART=0) — run: pm2 restart $APP_NAME --update-env"
  fi
done

echo
echo "Done. Verify a login returns 200:"
echo "  curl -s -o /dev/null -w '%{http_code}\\n' -X POST https://<tenant>/api/auth/local \\"
echo "    -H 'Content-Type: application/json' -d '{\"identifier\":\"...\",\"password\":\"...\"}'"
